# apply the instances and render the templates

- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  vars_files:
    - variables/variables.yml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-images
    - role: openstack-security-groups
    - role: openstack-instance
    - role: template-rendering
    - role: wait-connection
