# stop all the docker containers on the server

- name: copy the reset script
  become: yes
  copy:
    src: ./stop-containers.sh
    dest: /home/ubuntu/
    mode: 0777

- name: execute reset
  become: yes
  shell: /home/ubuntu/stop-containers.sh
